# Feature Switches
CONFIG_APP_FEATURE_METERING=y

# Subsystem Support
CONFIG_ADC=y
CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_SERIAL=y

# V32F20X Specific Driver Selection (Forcing inclusion)
CONFIG_ADC_V32F20X=y
CONFIG_V32F20X_GPIO=y
CONFIG_V32F20X_UART=y
CONFIG_CLOCK_CONTROL_V32F20X=y
CONFIG_RESET_V32F20X=y

# FlashDB
CONFIG_FLASHDB=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

# Shell
CONFIG_SHELL=y
CONFIG_SHELL_HISTORY=y
CONFIG_SHELL_BACKEND_SERIAL=y
