CONFIG_FLASH_BASE_ADDRESS=0x08000000
CONFIG_BOOT_MAX_IMG_SECTORS=144
CONFIG_BOOT_SWAP_USING_SCRATCH=n
CONFIG_BOOT_UPGRADE_ONLY=n

# Enable hardware watchdog support in MCUboot if needed
# CONFIG_WATCHDOG=y
