CONFIG_FLASH_BASE_ADDRESS=0x08000000
CONFIG_BOOT_MAX_IMG_SECTORS=144
CONFIG_BOOT_SWAP_USING_SCRATCH=y
CONFIG_BOOT_UPGRADE_ONLY=n
CONFIG_UPDATEABLE_IMAGES=2

# Serial Recovery for "Unbrickable" device
CONFIG_MCUBOOT_SERIAL=y
CONFIG_UART_CONSOLE=n
CONFIG_MCUMGR_TRANSPORT_UART=y
# Enable hardware watchdog support in MCUboot if needed
# CONFIG_WATCHDOG=y
