# Base configuration for vango_demo
CONFIG_LOG=y
CONFIG_APP_FEATURE_METERING=y
CONFIG_APP_FEATURE_COMMS=y

# Power Management
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y

# Base Hardware Support
CONFIG_SERIAL=y
CONFIG_GPIO=y
CONFIG_ADC=y
